### ISSUE TITLE
[BE] Complete "complex" queries 1 - Selection

### ISSUE THREAD

**Issue by michaelfromyeg** [emilyychenn/jSearch#10]
Create one query of this category. Provide an interface for the user to specify the selection conditions to be returned.

Example:
SELECT Field_01
FROM Table_01
WHERE Field_02 >= 0

**Comment by jjunhu** [comment]
SELECT company_id, position_title
FROM job_position_compensation
WHERE weekly_hours < 50

**Comment by jjunhu** [comment]
public JobPosition[] getPositionsWithSalary(int minSalary) {
        ArrayList<JobPosition> result = new ArrayList<JobPosition>();

        try {
            String query = "SELECT company_id, position_title, salary FROM job_position_compensation WHERE salary > ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, minSalary);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                JobPosition model = new JobPosition(rs.getString("company_id"),
                        rs.getString("position_title"),
                        rs.getInt("salary"));
                result.add(model);
            }

            rs.close();
            ps.close();
        } catch (SQLException e) {
            System.out.println(EXCEPTION_TAG + " " + e.getMessage());
        }

        return result.toArray(new JobPosition[result.size()]);
    }
