### ISSUE TITLE
[BE] Add more bootstrap SQL files

### ISSUE THREAD

**Issue by michaelfromyeg** [emilyychenn/jSearch#9]
Should have variety of SQL files for inserting chunks of data, and maybe some master shell script to insert each of them consecutively.

Also good to have a tear down script for emptying the database.

**Comment by emilyychenn** [comment]
hmm by inserting chunks of data do you mean INSERT statements into the db?? 

if so, i don't think we can do this... from the project rubric, under the SQL script section, one of the requirements is:

> A single script that could be used to create all the tables and data in the database.

but a tear down script sounds like a good idea!

**Comment by emilyychenn** [comment]
Closing this issue because I can't think of any instances when we would want a teardown script... or if it's worth the effort
